# Generated by Django 3.2.7 on 2021-09-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='New Quiz', max_length=255, verbose_name='Question Text'),
        ),
    ]
