# Generated by Django 2.2.5 on 2021-09-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20210929_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[(0, 'Fundamental'), (1, 'Basic'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], max_length=255, verbose_name='Difficulty Level'),
        ),
    ]
