# Generated by Django 2.2.5 on 2021-09-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20210930_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Fundamental'), (1, 'Basic'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], max_length=255, verbose_name='Difficulty Level'),
        ),
    ]
